<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);NU1701;NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalHost.Core\TerminalHost.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="EasyWindowsTerminalControl" Version="1.0.9" />
  </ItemGroup>

</Project>
