<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TerminalHost.macOS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalHost.Core\TerminalHost.Core.csproj" />
    <ProjectReference Include="../../lib/PtySharp/PtySharp.macOS/PtySharp.macOS.csproj" />
  </ItemGroup>

</Project>
